name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build
    steps:
      # setup ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler: '2.5.6'
          bundler-cache: true 

      # checkout
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Bundle Install
        run: bundle install
      
      - name: Jekyll Build
        run: jekyll build

      - uses: actions/upload-artifact@v4
        with:
          name: drop
          path: "_site"
          if-no-files-found: error
      
  deploy:
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: drop #$GITHUB_WORKSPACE
  
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_MUSHROOM_0CFDF7C10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: ${{ env.GITHUB_WORKSPACE }} #only the prebuilt site
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    needs: deploy
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_MUSHROOM_0CFDF7C10 }}
          action: "close"
